<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mdef</string>
	</array>
	<key>firstLineMatch</key>
	<string>@/</string>
	<key>name</key>
	<string>MenuDef</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*</string>
			<key>name</key>
			<string>meta.whitespace.leading</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#plistref</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#submenu_begin</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#submenu_end</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#divider</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\s*#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<key>divider</key>
		<dict>
			<key>match</key>
			<string>\s*----+\s*\n</string>
			<key>name</key>
			<string>support.other.protocol</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\S.*</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>plistref</key>
		<dict>
			<key>begin</key>
			<string>\s*(@)/</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.decorator</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<key>submenu_begin</key>
		<dict>
			<key>begin</key>
			<string>\s*&gt;</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.function</string>
		</dict>
		<key>submenu_end</key>
		<dict>
			<key>match</key>
			<string>\s*&lt;\s*\n</string>
			<key>name</key>
			<string>meta.function</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mdef</string>
	<key>uuid</key>
	<string>C252E0AB-EAEE-410A-9F72-E3723DE14035</string>
</dict>
</plist>
